### ISSUE TITLE
Formatting units - unicode or latex

### ISSUE THREAD

**Issue by tomhull** [OceanGlidersCommunity/Oxygen_SOP#142]
### Discussed in https://github.com/OceanGlidersCommunity/Oxygen_SOP/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **tomhull** October 16, 2021</sup>
We need to be consistent how we are going to render units.

Two options:

Latex math which gets converted to images in the final text, done like so
```
the oxygen measured $30~\mu mol~L^{-1}$
```
easy to type, but doesn't look as good in the text and can't be copied

or using unicode characters and tags.

```
the oxygen measured 30 μmol L<sup>-1</sup>
```

more fiddly to type because unless you have memorised the codes you need to copy paste the character, and the tags are harder to read in the markdown.

Personally, I vote for unicode.

![image](https://user-images.githubusercontent.com/2901405/137602133-cd84d6d9-5db1-47ea-9720-7546be29f03e.png)</div>

**Comment by isgiddy** [comment]
Ive had a little bit of a look at what is best for markdown, and I think unicode is the way forward as well.
Here is an explanation of github flavoured markdown for reference:  https://github.github.com/gfm/

**Comment by soerenthomsen** [comment]
Ok! So this is also good for jupyter books I assume?

**Comment by soerenthomsen** [comment]
Also vote for unicode!

**Comment by soerenthomsen** [comment]
I will implement unicode it through the document.

**Comment by soerenthomsen** [comment]
We decided for unicode also in the salinity and nitrate SOP so we can close this here.
