### ISSUE TITLE
correct/better organising of optode commands, firmware versions

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#144]
@s-pearce

"In section 3.4.1.2 # 3 it says to "Do Stop" is the command to stop the Aanderaa 4831/4330 from sampling and to use "CR + LF" in the terminal. This is a bit of a mixed message. In optode firmware versions smaller than 3.x.x (Framework 3), it did not require the "CR + LF", only the "CR" and the command to stop was "Do Stop". In 3.x.x and higher (as of 2021, in 5.x.x framework), the optode does require "CR+LF" and the command to stop was changed to only a "Stop", no longer requiring the "Do".
This is described in Appendix 11 "Product Change Notification: Framework 3" in the Aanderaa 4330/4835/4831 Optode manual. Anyway, nobody is likely to use firmware less than 3.x.x anymore, so I suggest that the "Do Stop" change to "Stop" above.
Also, I believe it was framework 3 that first allowed the SVU/Multipoint-calibration, and firmware less than 3.x.x only used the Mk2 equation.
-Stuart Pearce"

**Comment by soerenthomsen** [comment]
Thanks @s-pearce for raising this good point. We already discussed how we could better organise all these commands, firmware issue. As you state correctly the commands are changing with firmware versions and we also don't want to repeat all the commands here. 

In my view the best would be to have a short summary and even mention key commands, i.e. of the latest version but more importantly add links to all kind of manuals which are online available. 

I think it is a very valuable information, in particular for very new users. 

@tomhull @patricialg what do you think?

**Comment by tomhull** [comment]
I'm writing a section which summaries the commands and steps needed to calibrate each optode.
I'll run the procedure and double check as I think I have at least one now of every type of optode/firmware apart from the 5xxx series, I should also be able to add the RBRCoda as well.

- [ ] 3830 and 3835
- [ ] 4xxx pre framework 3
- [ ] 4xxx post framework 3
- [ ] RBRCoda

**Comment by soerenthomsen** [comment]
Thanks a lot Tom.

**Comment by soerenthomsen** [comment]
Hi @tomhull is this done?

**Comment by soerenthomsen** [comment]
I think we still need to remove the old version in the main text before close this or and refer to the new appendices. Right?
