### ISSUE TITLE
Cleaning/flushing/storage procedures for SBE43 DO sensor

### ISSUE THREAD

**Issue by richardsc** [OceanGlidersCommunity/Oxygen_SOP#146]
From a discussion with @soerenthomsen and Evi Bourma (@evibourma) there should be some clarity added about how to flush, clean, and store the SBE43 DO sensor on gliders. I *think* that this only applies to SeaExplorer gliders, as the DO sensor is not available as a dry-payload option (e.g. slocum and seaglider ... not sure about spray).

From Evi:
> We have extensively used the GPCTD with DO in our missions, so i am not familiar to other sensors' practices. Regarding the DO sensor, we usually disconnect it from the GPCTD and apply a special tube (with the sponge in the middle). We inject in the sponge a thin solution of Na2SO3 in order to consume the remaining oxygen in the sensor. The remaining oxygen can consume the chemical components used by the sensor for the calculation of the oxygen concentration.

From me:
> One point to consider is that we were advised to never rinse the SBE+O2 with a strong water jet (i.e. hose) as it can damage the membrane of the O2 sensor. One a syringe should be used to gently flush the system.

As a general note I have been recommending to colleagues to avoid the SBE43 on gliders, and instead opt for an optical sensor (e.g. Aanderra or RBR). Generally the SBE43 is supposed to be fairly reliable on CTD profiling systems, but we have found that it is very sensitive and just isn't well-suited to glider work. In cold conditions you have to keep the system from icing (hard to do when out on a boat for 2 hours in -10C ... we made an insulated "hood" and use handwarmers inside). Basically every time we have ever sent one back to SBE for service/calibration they have been unable to do a pre-calibration check (e.g. for drift) because they claim the membrane is broken. So we only ever have the factory calibrations (when it leaves) and never the post-deployment calibrations (before service) when it is sent back.

**Comment by patricialg** [comment]
Info added to the SOP, please, have a look at it.
I think we can close this issue now?

**Comment by soerenthomsen** [comment]
This can be closed now due to PR #215
