### ISSUE TITLE
Restructure: Make chapter "Sensor and Integration" 

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#155]
While uploading the Salinity SOP (online soon), @isgiddy and myself (@soerenthomsen) realized a slightly different structure at the beginning. 
- Introduction
- Sensors and Integration 
- Pre-deployment ...

At the moment we have sensors in the introduction and integration in pre-deployment etc. 

I think it would make sense to make a chapter "Sensor and Integration" just after the introduction.

**Comment by patricialg** [comment]
Agree with your suggestion :)

**Comment by soerenthomsen** [comment]
Ok as soon as I am done with this part of the salinity SOP I will start to restructure here too.

**Comment by patricialg** [comment]
I can do it while you are working on the Sal SOP, I assume it's nothing more than chaging headings? The main information should stay the same. Let me know ;)

**Comment by soerenthomsen** [comment]
No we have to create first a new section files called "oxygen_sensors_integration.md" and copy over the content. After we also have to change the Table of Content here: 
https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/_toc.yml 

But sure please go ahead via pull-request so i can review :)

**Comment by soerenthomsen** [comment]
Working on it now

**Comment by soerenthomsen** [comment]
@patricialg could you check directly on the jupyter book whether all migration worked fine?

**Comment by patricialg** [comment]
Perfect! Thanks :)
