### ISSUE TITLE
Optode calibration - how many points?

### ISSUE THREAD

**Issue by isgiddy** [OceanGlidersCommunity/Oxygen_SOP#157]
Section 4.5.1 recommends calibration at 2-point calibration of temperatures in the range of expected measurements. If the temperature range of planned measurements is small, (5 degrees celcius), is it still recommended to run at two temperatures?

Is it recommended to increase the number of temperature points if possible?

@patricialg @tomhull @hahn-johannes

**Comment by soerenthomsen** [comment]
I think this relates to the major issues #48 

In short the more the better and i my view are at least two different temperatures at 0/100 required. In your case i suggest to try to do even two low temperatures and a normal room temperature one

**Comment by soerenthomsen** [comment]
I close this and refer to #48
