### ISSUE TITLE
Mention Licenses in Jupyter Book deployment

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#174]
As pointed out by @paulineobps so far the licence is not clear when just looking at the Jupyter Book and it suggests that the The Jupyter Book community owns the copy right.
`By The Jupyter Book community
© Copyright 2021.`

We have to check with the jupyter book whether they own any copyright over the content of the deployment. If that is the case we have a problem. 

This issue is relevant for each SOP.

**Comment by jbusecke** [comment]
Interesting point. [Here] is some internal discussion about this topic, but I agree this is not entirely clear. We should probably track down the actual type of license that the jupyter project uses and then see if/how we can explicitly modify it for this project? 
It is also not at all clear if the copyright applies to the framework of jupyter book only or the content aswell.

**Comment by soerenthomsen** [comment]
Thanks @jbusecke for supporting this. There is nothing linked in your comment.

**Comment by isgiddy** [comment]
Just had a look into this a little. 

Jupyter Book is licensed under a BSD 3-Clause. See the link [here](https://github.com/executablebooks/jupyter-book/blob/master/LICENSE).  

The license footer can be edited in the default_config.yml file. (see [link](https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/default_config.yml)). Here the author and copyright can be edited. 

I had a look at some other jupyter books for reference. See screenshot example below:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/30691939/144248982-2239bc94-cc91-4373-9a76-e91658e1c9f2.png">

**Comment by soerenthomsen** [comment]
Thank you @isgiddy for checking this! Indeed this is very helpful. Also the example is very helpful. 

@jbusecke what do you think?

**Comment by jbusecke** [comment]
Sorry this is the link I meant to send: https://github.com/executablebooks/jupyter-book/issues/661. I am honestly not an expert on these specific things, and it seems like @isgiddy has now more expertise on this topic 😁

**Comment by paulineobps** [comment]
Thanks Isabelle

There are choices for licenses https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository.

Creative Commons are the most well-known licenses and the Creative Commons-Attribution-ShareAlike (CC-BY-SA 4.0 ) is the one to use if you are going to permit access and use by Commercial interests.

BSD 3-Clause "New" or "Revised" License - looks good but is for executable books?     Particularly like the 'prohibits others from using the name of the project or its contributors to promote derived products without written consent'
What will go into OBPS is a pdf with a CC License with the link to the GitHUB code repository in the metadata field?
BSD 3-Clause "New" or "Revised" License would cover the GitHub access.

I have not been in all the discussions so not totally sure of all the formats and componenets that will be produced for the SOP.

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, Wandelaarkaai 7/61, 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>



________________________________

**Comment by soerenthomsen** [comment]
From Pauline just post it here to ensure everyone reads it: 

"Dear Soeren

We discussed the SOP at our OBPS SG last week.   It will be a first, but the OBPS software can ingest Jupyter Notebook files.   In the metadata we will link to the GitHub repo.

I think from the previous emails the licenses are now agreed?

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/"

**Comment by soerenthomsen** [comment]
Great to hear @paulineobps that you discussed this SOP and our process at the OBPS SG and even nicer to hear that the OBPS software can ingest Jupyter Notebook files. 
Indeed linking the GitHub repo is key so that people always find the up to date version. This might also help to get more and new users who engage with the SOP after downloading it. 

Best wishes
Soeren

**Comment by soerenthomsen** [comment]
@isgiddy could you provide the link to the repo of the jupyter book example you screenshoted above?

**Comment by soerenthomsen** [comment]
This is solved via PR #187 and can be closed. Thanks @isgiddy for supporting this and implementing it directly into the Salinity SOP!
