### ISSUE TITLE
review DMQC section

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#19]
Parts of the DMQC chapter has still not been moved to GitHub and there might be some convergence needed related to the chapter "Sensor time response correction". 

@tomhull are you ok to take the lead on this?

**Comment by soerenthomsen** [comment]
The main content has been move by @tomhull via #43, it would be good if @gkrahmann and Mun Woo read this section and start a new issues in case they disagree or want to add content.

**Comment by soerenthomsen** [comment]
I gave it a 2nd read and corrected a few typos in #46.

**Comment by gkrahmann** [comment]
Hi all,
for the requested plots: 
Do we want to have similar plots for the different methods ?
Since I haven't yet made any plots, I can do whatever is preferred ?

**Comment by soerenthomsen** [comment]
Hi Gerd, thanks for engaging! 

Indeed good point. It would be great to show the same (similar) parameters for all different methods.
I suggest @tomhull and you decide which parameters should be shown in such an SOP here and we try to get similar plots for the other methods too.

**Comment by gkrahmann** [comment]
I have submitted a picture. Have a look at it, whether it makes sense this way. It is tricky to show everything in one plot.

**Comment by soerenthomsen** [comment]
Thanks Gerd. I merged it and it worked. I think for now we just try to make the DMQC chapter look ok for the community review. So all good.

**Comment by soerenthomsen** [comment]
TO DO: 
- [ ] get feedback from IMOS (Mun Woo) on their methods part
- [ ] ...

**Comment by soerenthomsen** [comment]
I close this and start a specific IMOS DMQC issue.
