### ISSUE TITLE
English language style

### ISSUE THREAD

**Issue by tomhull** [OceanGlidersCommunity/Oxygen_SOP#212]
I think we briefly talked about this at the start but we should be consistent with our language style.
Luckily there are tools for this.

At the moment we have a split between British and British (oxford) spellings. e.g.

 **British**             | **Oxford**              | **Australian**   | **Canadian**     | **American** 
-------------------------|-------------------------|------------------|------------------|--------------
 en-GB                   | en-GB-oxendict          | en-AU            | en-CA            | en-US        
 organisation            | organization            | organisation     | organization     | organization 
 realise                 | realize                 | realise          | realize          | realize      
 analyse                 | analyse                 | analyse          | analyze          | analyze      
 behaviour               | behaviour               | behaviour        | behaviour        | behavior     
 centre                  | centre                  | centre           | centre           | center       
 defence                 | defence                 | defence          | defence          | defense          
 programme               | programme               | program          | program(me)      | program      
 program (computer code) | program (computer code) |                  |                  |              
 disc                    | disc                    | disc             | disc             | disk         
 disk (computing)        | disk (computing)        | disk (computing) | disk (computing) |              
 ageing                  | ageing                  | aging            | aging            | aging        
 traveller               | traveller               | traveller        | traveller        | traveler     

While most UK newspapers and such write in British, Most journals including Nature, and UN documents uses oxford.

Happy to do either.

**Comment by soerenthomsen** [comment]
For me also both British or Oxford is fine. Is this also what Frontiers uses? So I let you two decide but will ensure it is the same for the other SOPs after.

**Comment by soerenthomsen** [comment]
Is there any way I can support this? I think it is the last issue we aim to close before submitting to OBPS beside the open PR about the 2 min stop.

**Comment by tomhull** [comment]
Hi Soren,

Sorry, meant to do it last week, it's near top of my list :D

**Comment by tomhull** [comment]
Yep, should have time tomorrow.

**Comment by soerenthomsen** [comment]
Great! @jbusecke as soon as this issue is closed we plan to build the pdf for release 1.0. 
Do you have capacity to support this process?

The plan is to 
1) create the pdf and a zip file of this repo 
2) Submit this to the OBPS system and get a doi
3) Make a release here on GitHub and link the doi

Does it make sense?

**Comment by jbusecke** [comment]
What is the actual timeline? 
If you plan to do this manually, I think all you need to do is issue a release on github and it will neatly package all the code into a zip file for you. That way you can always refer to that tag, even when the repo keeps evolving. 
How do you plan to generate the pdf? Just use jupyter book? That should be fairly simple.

**Comment by soerenthomsen** [comment]
Thanks @jbusecke for your quick response. I plan to create the pdf, zip file etc early next week and submit directly to the OBPS system. 

I think you created a pdf manually a while ago or? Seemed to work I remember. Yes using Jupyter book I think.

**Comment by jbusecke** [comment]
I think this is what I used: https://jupyterbook.org/en/stable/advanced/pdf.html

**Comment by soerenthomsen** [comment]
Ok lets fix this maybe together tomorrow @jbusecke. I open a new issue #220 
Will read your link before.
