### ISSUE TITLE
Suggested sampling period for optode deployment

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#22]
There was an open discussion on this what we can recommend here.

i.e Tania Morales raised the point: 
is it a recommended sampling period for every situation or is it totally dependent on the mission planning (objectives, battery life, etc)?

Is a general recommendation useful/possible, if not we should at least write what kind of thoughts have to go into this decision.

**Comment by tomhull** [comment]
I agree with Tania, but yes it is worth outlining what the considerations are, maybe with some specific examples.

Low sampling frequency makes lag correction more difficult, I would suggest if there is a strong oxycline to always sample at 5 s period for the region around the oxycline.

I'd also highlight that periodic dives with high frequency sampling may be more useful than continuous measurement at a lower frequency. i.e. 5 good dives could be better than 50 mediocre ones.

**Comment by soerenthomsen** [comment]
Yes makes sense to me. Would you mind adding this at the correct place so we can close the issue?

**Comment by soerenthomsen** [comment]
I drafted something based on your input @tomhull 

Please revise if needed here: #56
