### ISSUE TITLE
Cleaning up: remove pandoc actions

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#221]
Cleaning up the repo a bit before doing the release:

I think we can remove the pandoc html and pdf actions or?

https://github.com/OceanGlidersCommunity/Oxygen_SOP/actions/workflows/github-actions-pandoc-html.yml

https://github.com/OceanGlidersCommunity/Oxygen_SOP/actions/workflows/github-actions-pandoc-pdf.yml 

As we now build the book via jupyter books.

@tomhull ok for you?

**Comment by tomhull** [comment]
fine by me

**Comment by soerenthomsen** [comment]
PR #222 implements this issue
