### ISSUE TITLE
recommended configuration to compute DOXY

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/Oxygen_SOP#238]
In section [6.1](https://oceangliderscommunity.github.io/Oxygen_SOP/sections/oxygen_rtqc.html#required-metadata-and-real-time-data-processing) could you clarify the meaning of "recommended configuration" ? It is not clear to me whether the "salinity compensation of MOLAR_DOXY, pressure correction for pressure effect on quenching, temperature compensation" represent the recommended configuration individualy, or is it the combination of the three element listed here that is the recommended configuration.

**Comment by tomhull** [comment]
I suggest this section is rewritten to say: 
"Correction of oxygen concentration requires a configuration which includes salinity and pressure)".

**Comment by cgourcuf** [comment]
To be even more precise I would change "_Configurations for the calculation of DOXY are function..._" by "_Corrections for the estimation of DOXY are function..._" and "_The recommended configurations..._" in the 2nd sentence by "_The recommended corrections..._"
