### ISSUE TITLE
License

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#31]
We have to decide on a licence. I will discuss with Ocean Best Practice System (OBPS) and Frontiers Journal to ensure we do all correct. 

Likely we will choose a CC https://creativecommons.org Licence.

If there is anyone with experience on this please let us know.

**Comment by tomhull** [comment]
I think CC is the right choice.

**Comment by soerenthomsen** [comment]
Yep but which exactly we might have to elaborate with the Journal we plan to publish and OBPS or? Also this impacts the choice of images we can take etc.

**Comment by soerenthomsen** [comment]
I suggest we choose: [CC-BY 2.0](https://creativecommons.org/licenses/by/2.0/)

Any thoughts. @gkrahmann @bastienqueste @tomhull

**Comment by soerenthomsen** [comment]
We might also go for 

CC BY-SA: This license allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator. The license allows for commercial use. If you remix, adapt, or build upon the material, you must license the modified material under identical terms.
- CC BY-SA includes the following elements:
- BY  – Credit must be given to the creator
- SA  – Adaptations must be shared under the same terms

I will also elaborate with the funders EuroSea and GROOMII.

**Comment by gkrahmann** [comment]
Just as a comment:
Forcing derived works to license under identical terms often leads to problems. 
The code (or texts) where you include the derived works may require a different license and then this means
that it **cannot** be properly licensed and included.
If there is a way that avoids the 'identical', then I would prefer that way.

**Comment by soerenthomsen** [comment]
I close this for now.
