### ISSUE TITLE
Add automated test of valid PDF

### ISSUE THREAD

**Issue by tomhull** [OceanGlidersCommunity/Oxygen_SOP#35]
Someone (me) needs to set up automated testing of the PDF trigged when a pull request is submitted.

**Comment by soerenthomsen** [comment]
Right now I can only build a pdf if I turn off the branch protection role (1 review required). But just build a new pdf after your DMQC input. Worked!

**Comment by tomhull** [comment]
So, couple of options.
I can make it so when you run the action to build the PDF it doesn't commit the new file.
It could add it to the current release, or it just gets attached to the end of the job when you call it (and not updated in the repository).
I can make a seperate job to add a new version.
any preference?

For the HTML, It'll be on it's own branch at all times mirroring the main one.
I'll set it up on the test_SOP repository first, just so i don't break things.

**Comment by soerenthomsen** [comment]
I am not sure tbh. Let's discuss this together with @jbusecke this afternoon.

**Comment by soerenthomsen** [comment]
When doing this we also have to solve issues related to formulas etc

**Comment by soerenthomsen** [comment]
Jupyter Books and @jbusecke solved this issue! Thanks!

**Comment by jbusecke** [comment]
I think we could still provide a pre-made PDF in the repo as well, if that is desired?

**Comment by tomhull** [comment]
I think it's we probably only need one when we do a release.

**Comment by soerenthomsen** [comment]
I agree. A pdf after a major release, i.e. after the community review makes sense but not required each time.
