### ISSUE TITLE
add all names to image permissions.md

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#42]
Everyone who contributed an image where they hold the copyright please add your name etc here:
https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/images/permissions.md

**Comment by soerenthomsen** [comment]
The pull-request  #90 by @patricialg updated a few names

**Comment by patricialg** [comment]
To avoid using Aanderaa photo of 3 oxygen sensors, I have another photo of all Aanderaa sensors and with red arrows  to point the oxygen sensors (see image attached). Do you think this one will be better? Do you prefer without the arrows?
I have another option too, asking MARS at NOC to let me some optodes and make a similar photo to the Aanderaa web page photo. Please, let me know and I'll update the photo ;) 
![AaanderaasensorsAll](https://user-images.githubusercontent.com/13015381/136002627-f99c9cfe-c5fb-4cc4-8cc4-68056c274eee.png)

**Comment by soerenthomsen** [comment]
@patricialg I like this image with the red errors. You can cut out the lower 1/3 of the image I guess.

**Comment by patricialg** [comment]
Image is now in the folder. I´ll add it next to the Introduction section

**Comment by soerenthomsen** [comment]
@tomhull is [this](https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/images/slocum.jpg) image from you? if not do you have a similar one with copy right? After that we could close this issue!

**Comment by soerenthomsen** [comment]
Or @gkrahmann do you have an images similar to this one? https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/images/slocum.jpg 
We are not sure about the copyright and would just replace it to be able to close this and submit to the OBPS.

**Comment by gkrahmann** [comment]
We can make some, if necessary.
Shall I ask Christian ?

**Comment by soerenthomsen** [comment]
Would be great! Thanks a lot! Tom is on a cruise this week and we aim to close this as far as possible to submit to OBPS.

**Comment by soerenthomsen** [comment]
This can be closed now
