### ISSUE TITLE
discussion on experimenting with copper-coating

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#49]
Copied over from the Google Doc

@tomhull "I had the idea of copper-coating the foil holder (the plastic disk which keeps the foil in place), but I was concerned with galvanic corrosion. currently testing it with a broken optode on a mooring."

@gkrahmann "I remember we had corrosion on moored optodes exactly there even without copper. Don't remember where and when, but I could search for pictures. So be careful to use plastic separators to avoid contact between the metals."

@tomhull "That would be good to include. You've reminded me of the problems we've had with the standard 10 pin lemo connectors that most optodes have!"

@hahn-johannes "These corrosions, Gerd is talking about, only happened on optodes with blue housing (4330). Not on the 3830 optodes with titan housing."

**Comment by soerenthomsen** [comment]
@tomhull I think this is included now in 4.3 or?
https://oceangliderscommunity.github.io/Oxygen_SOP/sections/oxygen_pre_deployment.html?highlight=copper 

So can we close this or is there any information which has to be added to the text before closing this issue?

**Comment by patricialg** [comment]
can we close this issue? @soerenthomsen @tomhull
