### ISSUE TITLE
how many combined up and downs needed for good regression / time response correction

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#51]
@bastienqueste: 

"From experience, I find that anything less than 10 dives with both up and down for regressing is insufficient (whether it's Salinity, oxygen or flight model lags).
I think best practice should just be to get as many pairs of up and down as possible. It's the one golden benefit of gliders, it really helps with assessing data quality and regressing. Basically no other platform has this advantage and IMHO it should be emphasised."

**Comment by gkrahmann** [comment]
At GEOMAR we usually do a minimum of one up-down day per week of the deployment. An important point is to cover the whole deployment with up-down pairs to be able to detect developments of the sensors. For salinity we do the same.
This one day per week usually gives enough pairs for assessing data quality and determining the coefficients.

**Comment by soerenthomsen** [comment]
Thanks @bastienqueste and @gkrahmann for your input. Would you mind reviewing this 3 sentence section: 
Gather data to help correct for sensor response time
https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/oxygen.md#gather-data-to-help-correct-for-sensor-response-time

at the moment we write:
`Regular up- and down casts are needed to estimate and correct for the sensor response time. Combined up- and downcasts should be carried out at least every week and particularly at the beginning and at the end of the deployment. One to two days per week appear to be a reasonable compromise between energy saving and calibration quality. If bio-fouling is expected during the deployment it is better to collect up-down pairs earlier rather than later.`

and decide whether this discussion is properly captured there?

**Comment by soerenthomsen** [comment]
I think it is well captured. So I close this. 
@isgiddy maybe take a not for the salinity SOP to suggest the same.
