### ISSUE TITLE
review figure captions

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#73]
So far the figure captions are not build in jupyter book

**Comment by soerenthomsen** [comment]
I adapted all figure captions. Would be great if someone could review all figures and check that everything is there. 

Still to do:
- [ ] referencing figures inside the text

**Comment by soerenthomsen** [comment]
I references the figures now with {numref}`XXXX`

**Comment by jbusecke** [comment]
I took a quick look and they seem to be all there!

@soerenthomsen are you writing on a guide how to reference papers, do captions in figures etc? I think it would be nice to have a very brief part of the README that explains this?

**Comment by soerenthomsen** [comment]
hi @jbusecke thanks. 

I think for now I will mainly write a simple guide how to make general comments i.e. via Jupyter book. During the community review the lead authors will take care of implementing the suggestions to keep things more organised.
