### ISSUE TITLE
review IMOS DMQC section

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#80]
@tomhull raised this question.
"is the IMOS correction done in phase or oxygen? "
I guess Mun Woo can answer this. 

- [ ] review of overall IMOS DMQC section by Mun Woo

This relates to this chapter [here](https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/sections/oxygen_dmqc.md#time-response-correction-2---imos)

**Comment by soerenthomsen** [comment]
@tomhull please have a look here http://content.aodn.org.au/Documents/IMOS/Facilities/Ocean_glider/Delayed_Mode_QAQC_Best_Practice_Manual_OceanGliders_LATEST.pdf section 3.2.2.2 Time lag correction

As I understand the correction is done in phase. 

`Time taken for the Optode sensor to respond while taking measurements results in a time lag that must be corrected. The lag is relatively long (of the order of 20s, according to the manufacturer). A similar method to that previously used for correcting CTD temperature time lag is also applied here to correct the time lag in the Optode BPHASE:
1) At each 1 s time shift, RMS difference and BIAS values are computed for every pair of descent and ascent profile, and the median found;
2) The process is repeated for each subsequent time shift, resulting in a graph like Figure 25.
3) The BPHASE data is then corrected using the time shift found to result in the smallest RMS
difference value (e.g. 26s for the Kimberley20120727 mission (Figure 25)).`

**Comment by soerenthomsen** [comment]
@tomhull can we close this issue?

**Comment by tomhull** [comment]
yes, I think so
